name: roro_medicine_reminder
description: FYP2 2021/2022 RORO -Medicine Reminder

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_calendar: ^20.1.52
  fluttertoast: ^8.0.9
  move_to_background: ^1.0.2
  firebase_storage: ^10.2.12
  image_picker: ^0.8.5
  intl: ^0.17.0
  # grouped_buttons removed - not null-safe (incompatible with Dart SDK >=3)
  device_preview: ^1.0.0
  shared_preferences: ^2.0.13
  flutter_local_notifications: ^9.4.0
  email_auth: ^1.0.0
  flutter_svg: ^1.0.3
  material_design_icons_flutter: ^5.0.6595
  line_icons: ^2.0.0
  provider: ^6.0.2
  firebase_messaging: ^11.4.0
  qr_flutter: ^4.0.0
  flutter_neumorphic: ^3.0.3


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  # fab_action_menu removed - not null-safe (incompatible with Dart SDK >=3)
  firebase_auth: ^3.11.2
  cloud_firestore: ^3.1.12
  otp_text_field: ^1.1.2
  flutter_secure_storage: ^5.0.2
  google_sign_in: ^5.3.0
  firebase_core: ^1.24.0
  otp_autofill: ^2.1.0
  alt_sms_autofill: ^1.0.0
  flutter_datetime_picker: ^1.5.1
  auto_size_text: ^3.0.0
  flare_flutter: ^3.0.2
  rxdart: ^0.27.3
  sprintf: ^6.0.0
  flutter_native_timezone: ^2.0.0
  # sweetalert removed - not null-safe (Dart SDK >=3 requires null-safety)
  # charts_flutter removed - incompatible with intl 0.18.1 / Dart 3
 
  flutter_spinkit: ^5.1.0
  flutter_sms: ^2.3.2
  url_launcher: ^6.1.7
  http: ^0.13.5
  geolocator: ^8.2.1
  sqflite: ^2.0.2+1
  path_provider: ^2.0.10
  font_awesome_flutter: ^10.1.0
  location: ^4.4.0
  flutter_staggered_grid_view: ^0.6.1
  geocoding: ^2.0.4
  get_it: ^7.2.0
  flutter_downloader: ^1.7.4
  permission_handler_android: ^9.0.2
  permission_handler_platform_interface: ^3.7.0
  permission_handler: ^9.2.0
  google_ml_kit: ^0.11.0
  google_ml_vision: ^0.0.7
  flutter_material_pickers: ^3.1.0
  open_settings: ^2.0.2
  settings_ui: ^2.0.2
  package_info: ^2.0.2
  any_link_preview: ^2.0.8
  expandable: ^5.0.1
  android_alarm_manager_plus: ^2.0.5
  flutter_ringtone_player: ^3.2.0
  flutter_dotenv: ^6.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  path: ^1.7.0
  flutter_lints: ^2.0.0


flutter_icons:
  image_path: "assets/images/roroicon.png"
  android: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Light.ttf
        - asset: assets/fonts/Mulish-SemiBold.ttf
        - asset: assets/fonts/Capsules.ttf



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true

dependency_overrides:
  intl: ^0.17.0
